version: '3.8'

services:
  # zookeeperservice:
  #   image: wurstmeister/zookeeper
  #   ports:
  #     - "2181:2181"

  # kafkaservice:
  #   image: apache/kafka
  #   ports:
  #     - "9092:9092"
  #   environment:
  #     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafkaservice:9092
  #     KAFKA_ZOOKEEPER_CONNECT: zookeeperservice:2181
  #   depends_on:
  #     - zookeeperservice
  redisservice:
    image: redis
    ports:
      - ""
    
  postgresservice:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: postgres

  brokerservice:
    build:
      context: ../consumer/
      dockerfile: Dockerfile
    environment:
      NODEMAILER_USER: khushalbhasin4488@gmail.com  
      NODEMAILER_PASS:  
      KAFKA_BROKER: kafkaservice:9092
    depends_on:
      - kafkaservice

  hooksservice:
    build:
      context: ../hooks/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - postgresservice  

  processorservice:
    build:
      context: ../processor/
      dockerfile: Dockerfile
    depends_on:
      - kafkaservice
      - postgresservice
