version: '3.8'

services:
  redisservice:
    image: redis

  postgresservice:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: postgres

  consumerservice:
    build:
      context: ./consumer/
      dockerfile: dockerfile
    environment:
      NODEMAILER_USER: khushalbhasin4488@gmail.com  
      NODEMAILER_PASS: 123  
      NODEMAILER_HOST: smtp.gmail.com  # Corrected typo (NODEMAILER_HOST instead of NODEmAILER_HOST)
      REDIS_URL: redis://redisservice:6379  # Set Redis connection URL

  hooksservice:
    build:
      context: ./hooks/
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgres://postgres:mysecretpassword@postgresservice:5432/postgres
    depends_on:
      - redisservice
      - postgresservice  

  processorservice:
    build:
      context: ./processor/
      dockerfile: Dockerfile
    depends_on:
      - postgresservice
      - redisservice

  apiservice:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - postgresservice
    
  frontendservice:
    build:
      context: ./automotion-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - apiservice
